---
title: 주피터 노트북 테스트
categories: [study]
comments: true
---

## jupyter notebook 을 post 화 하기

1. anaconda prompt 를 실행.
2. directory 를 레포 root로 이동
3. new_post.sh notebook_name.ipynb

In [2]:
import numpy as np

a = np.zeros(shape=(3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
