---
title: 주피터 노트북 테스트
categories: [study]
comments: true
---

## jupyter notebook 을 post 화 하기

1. anaconda prompt 를 실행.
2. directory 를 레포 root로 이동
3. new_post.sh notebook_name.ipynb

In [2]:
import numpy as np

a = np.zeros(shape=(3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
import pandas as pd
%matplotlib inline
df = pd.read_csv("http://vincentarelbundock.github.io/Rdatasets/csv/datasets/crimtab.csv")
print (df.shape)
df

(924, 4)


Unnamed: 0  Var1    Var2  Freq
0             1   9.4  142.24     0
1             2   9.5  142.24     0
2             3   9.6  142.24     0
3             4   9.7  142.24     0
4             5   9.8  142.24     0
..          ...   ...     ...   ...
919         920  13.1  195.58     0
920         921  13.2  195.58     0
921         922  13.3  195.58     0
922         923  13.4  195.58     0
923         924  13.5  195.58     0

[924 rows x 4 columns]